/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adruinogui;

/**
 *
 * @author Klaus
 */
public class DistanceFrame extends javax.swing.JFrame {

    private static final double MAX_DIST = 3200;
    
    private double dist;
  
  /**
   * Creates new form DistanceFrame
   */
  public DistanceFrame() {
    initComponents();
  }

  public void setDistance(double dist){
    this.dist = dist;
    calc();
  }
  
  private void calc(){
    pnlDist.setBounds(pnlDist.getX(),pnlDist.getY(), (int)(this.getWidth() / MAX_DIST * dist), pnlDist.getHeight());
    this.repaint();
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlDist = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

    pnlDist.setBackground(new java.awt.Color(255, 0, 0));

    javax.swing.GroupLayout pnlDistLayout = new javax.swing.GroupLayout(pnlDist);
    pnlDist.setLayout(pnlDistLayout);
    pnlDistLayout.setHorizontalGroup(
      pnlDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    pnlDistLayout.setVerticalGroup(
      pnlDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    getContentPane().add(pnlDist);

    pack();
  }// </editor-fold>//GEN-END:initComponents



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel pnlDist;
  // End of variables declaration//GEN-END:variables
}
